### ISSUE TITLE
BLHeli Suite Motor Test Fail

### ISSUE THREAD

**Issue by suckmo** [ArduPilot/ChibiOS#21]
I apologize if this isnt the correct way to flag this issue. I was following the tutorial on Ardupilot that ref this page. Im new to this, and didnt see anything that would redirect me to a forum. if this isnt the correct way to go about this please enlighten me where i should be posting stuff like this. Anyways, Im currently running 

PX4 3DR Flight Controller with v4.0.3
Tekko32 35A 4 in 1 esc with V32.7
BlHeliSuite32715
MissionPlanner 1.3.73 
on a windows64 based machine (Beside Windows, everything is the latest release)

I talk to the AP through Radio and talk to the ESC via the USB port on the AP

So Ive followed the dshot/passthrough tutorial posted by Ardu found here:

[url]https://ardupilot.org/copter/docs/common-blheli32-passthru.html[/url]

With my current params, I can see live telemetry via the OSD  and LOGS in MP. The issue I have is when I interface with the ESC in B LHeliSuite. I can connect to the esc, read it,  flash it, configure it, read verbose messages, etc.... however when i go into the "Motors" Tab (timestamp 12.37 in the walkthrough video) and attempt to use any of the sliders the GUI closes the ESC connection. Basically I check that my props are removed, It reduces the number of motors to four ( the correct amount) and states the "Controls Enabled"... When i grab any of the slides, they only let me increase signal from 1000 to 1010, runs for about 1 second and then closes the connection in the GUI, as if i never checked off the Props removed box. I have no clue if this is an ESC error, a param I missed, a GUI error, etc.... any guidance if greatly appreciated. I attache a copy of the verbose code when attmpting the motor test in BLHeli and my current params. Let me know if there is anything else I can clarify

[PX4 3DR Passthru Params.txt](https://github.com/ArduPilot/ChibiOS/files/5202081/PX4.3DR.Passthru.Params.txt)

[VBoseCode_MTFailure.txt](https://github.com/ArduPilot/ChibiOS/files/5202070/VBoseCode_MTFailure.txt)

**Comment by suckmo** [comment]
[arming check is 0.txt](https://github.com/ArduPilot/ChibiOS/files/5202900/arming.check.is.0.txt)
 
Set arming_chk=0 elimantes prearm failures.... but still fails BLHeli side

**Comment by suckmo** [comment]
So I rolled back the BLHeliSuite to 32610 and it worked without any other mods to params. this is a BLHeli GUI error... but why?

**Comment by IamPete1** [comment]
@suckmo since you got this working in the end I'm going to close this. Sorry no one saw is, it would have had move visibility over on the main AP issues list, feel free to open one over there if its still not working.
