### ISSUE TITLE
can't resolve file

### ISSUE THREAD

**Issue by keefer223** [ArduPilot/ChibiOS#90]
/modules/ChibiOS/ext/fatfs/documents/00index_e.html

 8    <link rel="start" title="Site Top" href="../../">
 9    **<link rel="up" title="Freewares" href="../../fsw_e.html">**
10   <link rel="stylesheet" href="css_e.css" type="text/css" media="screen" title="ELM Default">

I couldn't get ardupilot to run.

Debian 12, python 3.11,

so I loaded ardupilot into pycharm. Unfortunately, pycharm couldn't find fsw_e.html.
I even did a search of ardupilot and was still not able to find fsw_e.html,

**Comment by andyp1per** [comment]
ArduPilot is a C++ application
